version: "3.8"

services:
  mysql:
    image: mysql:8
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=bowling

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports: 
      - 3000:3000
    volumes: 
      - ./server:/usr/src/app
    environment: 
      - MYSQL_HOST=mysql

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports: 
      - 8080:8080
    volumes: 
      - ./client:/usr/src/app    